### PR TITLE
Display package maintainers more prominently

### PR DESCRIPTION
**Pull request by zeke**
A familiar author can be an indication of package quality. This PR updates the maintainer list on the package page to appear more prominently in the sidebar. Above the fold, as they say. The gravatars are smaller now, so I added tipsy tool tips (kinda like the ones on github, but ours are npm red).

Here's what a package with many maintainers looks like:

screen shot 2015-01-08 at 2 40 13 pm

When there's only one maintainer, the username is displayed beside the gravatar:

screen shot 2015-01-08 at 2 40 35 pm

### CODE REVIEW

**Comment by zeke** [comment]
cc @rod11, who has :racehorse: in this race

**Comment by zeke** [comment]
Getting more above the fold, thanks to a few iterations with @seldo

- show last publisher's gravatar atop sidebar
- remove "package info" heading
- only show maintainers section if there's more than one
- display number of package releases

A package with a single maintainer looks like this:

screen shot 2015-01-08 at 4 23 36 pm

A package with multiple maintainers looks like this:

screen shot 2015-01-08 at 4 23 43 pm

**Comment by seldo** [comment]
I like this a lot. This is a really fiddly set of trade-offs but this is a big improvement.

**Comment by isaacs** [comment]
<3 <3 <3 <3 <3

**Comment by rod11** [comment]
LOVE IT!!!! LOVE LOVE LOVE

**Comment by zeke** [comment]
Fixed!

screen shot 2015-01-12 at 3 13 28 pm

**Pull request merged**
