### PR TITLE
Fix constrained width on nav

### LINKED ISSUE #1681: magic number in nav CSS
looks like the first anchor element is left aligned, while all others are right aligned
this supports the idea that the first anchor will be the npm-expansions anchor, but this is not always true

e.g.

```
nav
  div.container
    a(href="http://www.npmjs.com/on-site") npm On-Site
    a(href="https://www.npmjs.com/private-packages") npm Private Packages
    a(href="https://www.npmjs.com/open-source") npm Open Source
    a(href="https://www.npmjs.com/support") support
```

produces 
screenshot 2015-12-18 at 4 54 04 pm

### PR DESCRIPTION
**Pull request by ncawthon**
Fixes #1681

### CODE REVIEW

**Comment by ncawthon** [comment]
i know there's a bunch of rando commits in here. sorry about that, it took me awhile to get my rebase master right...

**Comment by aredridel** [comment]
Awesome. Want to pair on fixing those commit messages?

'cause now it's even more confusing: The commit that says it's a merge of master isn't a merge at all.

**Comment by aredridel** [comment]
And in fact, that's unrelated changes that don't need to be in your branch I think

**Comment by aredridel** [comment]
LGTM!

**Pull request merged**
