### PR TITLE
added counts of contributors to github stats on package page for #508

### PR DESCRIPTION
**Pull request by coleGillespie**
followed current paradigm. may want to re order the list items on the right side of the page.

### CODE REVIEW

**Comment by zeke** [comment]
Awesome!

I see one potential snag. Currently the GitHub API base URL is added to the HTML page as a data attribute only if `bugs.url` is defined in package.json. I think we should move the `if ghapi` conditional out of `bugs` and into `repository` so it has a greater chance of being included in the template, because most package.json files define `repository`, whereas `bugs` is less commonly included.

Does that make sense, @coleGillespie?

**Comment by coleGillespie** [comment]
@zeke got it, let me have another pass at this and see what i can do

**Comment by coleGillespie** [comment]
@zeke is this what you were looking for?

**Comment by zeke** [comment]
I think I led you astray. I was thinking the ghapi data attribute should be attached to the repository element, as opposed to the contributors or issues elements. But now that I think about it this may complicate things. I would revert that data attribute change and leave it where it was.

Another thing: The GitHub API returns 30 results by default, and a max of 100. But popular projects have well over 100 contributors (express has 166). There's a little trick you can do with the GitHub API to get around this: ask for one single result in your API call, then look at the response headers to find out how many "pages" there are. That's what we're currently doing to get issue/PR counts:

```js
Number(parseLinkHeader(xhr.getResponseHeader("Link")).last.page)
```

https://github.com/npm/newww/blob/1e0ebe7158f982e9fbd3ac0a46086d80e2415346/assets/scripts/github.js#L50

**Comment by coleGillespie** [comment]
https://api.github.com/repos/joyent/node/contributors

**Comment by zeke** [comment]
Try this:

```sh
curl -i https://api.github.com/repos/joyent/node/contributors?per_page=1
```

In the response headers, you'll see:

```
Link: <https://api.github.com/repositories/211666/contributors?per_page=1&page=2>; rel="next", <https://api.github.com/repositories/211666/contributors?per_page=1&page=548>; rel="last"
```

The `last` value (548) is the number of contributors

**Comment by coleGillespie** [comment]
ha, ok lets see what i can do

**Comment by zeke** [comment]
@coleGillespie I'm gonna put this on ice. Feel free to re-open if you end up working on it more. Thanks!

**Pull request closed without merging**
