### PR TITLE
allow empty org to still have users added by the org admin

### PR DESCRIPTION
**Pull request by rockbot**
Before this PR: if a user deleted themselves from their org before adding a new member to the org, the user would be unable to add any new members to the org (because the table to do so would disappear)

After this PR: an org creator can delete themselves but continue adding others :-)

### CODE REVIEW

**Comment by jefflembeck** [comment]
Good catch.

handlebars has a sweet shortcut for the `if each /each else /if` pattern with `each else /each`

**Comment by aredridel** [comment]
Oh shiny, @jefflembeck

**Comment by aredridel** [comment]
Works!

**Comment by jefflembeck** [comment]
\o/ :sheep:

**Pull request merged**
