### PR TITLE
Adds support for anchor links and adds heading anchor links

### PR DESCRIPTION
**Pull request by mikaelbr**
_Congratulations on the new site, by the way!_

Anchor links (#some-slug) didn't seem to pass the sanitation step, so I added a conditional to support it.

This PR also adds "Github style" heading anchor links. This way people can refer to specific part of the README (a anchor-icon is visible on heading hover). See image below.

I don't know if you are interested in this feature, but it's something I've been missing in the readmes, so I thought I'd give it a try.

anchorlinks

### CODE REVIEW

**Comment by mikaelbr** [comment]
It seems this has been implemented a different way, so this can be closed, @zeke ?

**Comment by zeke** [comment]
It has indeed. Thanks for noticing.

The readme changes we just deployed are proving to be a bit volatile for some packages, so we're rolling back for now. But yes, the deep links are coming! :)

**Comment by mikaelbr** [comment]
Sounds good. It looked very nice the packages I saw. Good job.

**Comment by zeke** [comment]
Thanks for the kind words; they're good to hear in these sad rollbacky moments.

**Pull request closed without merging**
