### PR TITLE
Add a shrinkwrap

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
I was thinking manually: with npm 3, we can update with --save, and the shrinkwrap is updated -- it just means we check in an exact pattern for how things should happen in prod, just as we've tested it. The workflow is relatively low friction that way, and doesn't need much automating.

**Comment by aredridel** [comment]
Yeah, we do. Shrinkwraps really only work well on 3.

**Comment by aredridel** [comment]
The shrinkwrap in this PR will have to be regenerated before merging, but yeah, let's get this outstanding and start the work.

**Comment by aredridel** [comment]
@ceejbot @mmalecki any thoughts on how difficult it is to roll out npm 3? Any risks you can think of?

**Comment by mmalecki** [comment]
@aredridel not hard at all. Also no risks I can think of right now.  I think @ceejbot had some concerns about initial npm 3 versions, but those problems should be solved by now.

**Comment by aredridel** [comment]
Needs to be updated.

**Pull request merged**
