### PR TITLE
Updated "cheerio" package dependency.

### PR DESCRIPTION
**Pull request by jonathanmarvens**

### CODE REVIEW

**Comment by aredridel** [comment]
Is 0.19 to 0.20 a breaking change?

**Comment by jonathanmarvens** [comment]
Argh. I don't remember exactly, TBH, @aredridel, but if it was, it definitely wasn't something that should affect us. (I should've kept notes!)

**Comment by jonathanmarvens** [comment]
@aredridel: https://github.com/cheeriojs/cheerio/blob/f500197155d4e03e7e03fa51925d9cc0aca778fc/History.md ← Here are the release notes.

**Comment by aredridel** [comment]
Looks shippable. I wish they'd adopt unambiguous semver.

**Pull request merged**
