### PR TITLE
first run at fixing painfully slow user profile pages (fixes #854)

### LINKED ISSUE #854: listing all modules for power user is painfully slow
Listing all the packages for a power user, e.g., substack, is painfully slow and sometimes results in `503`s.

screen shot 2015-04-09 at 12 58 49 pm

Given that we can paginate any of these queries now, it would be cool if we could figure out a UI for pagination on a user's profile page.

I think this will become more of an issue as development shops publish dozens of private modules.

### PR DESCRIPTION
**Pull request by rockbot**
This still needs tests (will get to it on Monday), but here's the low-down:

1) I'm now chopping up the package list to 100, and adding more via ajax on user request
2) I've created a template to make adding the packages to the page easier, but had to remove the `truncate` helper function because I'm not sure how to add that back in (can look into it next week, though if @zeke knows, that'd be mega helpful)
3) I'm using a huge button to handle the user-request bits... not sure if a different styling would be better?

feedback very much welcome!!

### CODE REVIEW

**Comment by bcoe** [comment]
\o/ I'm so excited about this, one of my few complaints about the website (which I think very highly of).

**Comment by zeke** [comment]
Looking good. :)

**Comment by zeke** [comment]
Looks like the build is failing on Travis:

```
Error: Cannot find module 'lodash._basecopy'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/npm/newww/node_modules/gulp-stylus/node_modules/gulp-util/node_modules/lodash.template/index.js:9:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by zeke** [comment]
I've tested this locally. It works nicely!

A few thoughts:

- The button says 'view more packages'. Mentioning the username might help clarify what the button will do: `view more packages by substack`
- The front-end template differs slightly from the one used by the server, in that it doesn't call the `truncate` method on the package name. For a good example of how to make helpers like `truncate` available on the frontend, see [https://github.com/epeli/node-hbsfy#helpers]. Ideally, the server and browser would share the template, as is done with the [templates/partials/collaborator.hbs]([templates/partials/collaborator.hbs]). I've been thinking we should retire `/assets/templates/*.hbs`, and keep *all* templates in `/templates`, but I'm not sure what's best.

**Comment by zeke** [comment]
All that said, we can ship this as-is if you want, and create issues to resolve the template discrepancy (the `truncate` part in particular, as I'm sure this will bite us again).

**Pull request merged**
