### PR TITLE
Added docpad to what npm is for

### PR DESCRIPTION
**Pull request by balupton**
[DocPad](https://docpad.org/)'s plugin system is powered by npm: https://www.npmjs.com/search?q=docpad-plugin and was one of the first (if not the first) plugin system for node

### CODE REVIEW

**Comment by zeke** [comment]
I'm not inclined to merge this as I've never heard of docpad, but I'll defer to @rockbot to make the call.

**Comment by balupton** [comment]
It's the first/oldest and largest static site generator for Node. http://nodeup.com/seventynine

**Comment by balupton** [comment]
No merge? It's more popular and used than some other things listed in that listing...

**Comment by zeke** [comment]
you convinced me. :)

**Pull request merged**
