### PR TITLE
npm is for iojs

### PR DESCRIPTION
**Pull request by zeke**
screen shot 2015-01-22 at 11 10 09 am

### CODE REVIEW

**Comment by othiym23** [comment]
pssst.... io **dot** js

**Comment by zeke** [comment]
But what about the website, the github org, and the binary?

- https://github.com/iojs
- https://iojs.org/
- ~/.nvm/versions/io.js/v1.0.3/bin/iojs

**Comment by micnic** [comment]
@zeke https://github.com/iojs/io.js#is-it-iojs-or-iojs-or-iojs-or-iojs-or-iojs :)

**Comment by zeke** [comment]
I concede.

**Pull request merged**
