### PR TITLE
fix(CSS): change imports order since colors are needed by variables

### PR DESCRIPTION
**Pull request by Delapouite**
Hi

variables.styl needs the color `npmred`
https://github.com/npm/newww/blob/master/assets/styles/variables.styl#L54

reset.styl also need colors to define the `hr` element 
https://github.com/npm/newww/blob/master/assets/styles/reset.styl#L27

and the `body` element
https://github.com/npm/newww/blob/master/assets/styles/reset.styl#L74-L75

Therefore, colors.styl should be imported first.

### CODE REVIEW

**Comment by aredridel** [comment]
Is this not resolved at compile time, regardless of order? Or is the actually introducing changes to the output

**Comment by Delapouite** [comment]
Thanks for having a look at this PR.

If you search in the current CSS file deployed on the website for `npmred`: 
https://www.npmjs.com/static/css/index.7e101822.css

```css
.red-on-hover:hover,
.sidebar a:hover,
.package-widget a.name:hover,
.package-widget .quiet a:hover,
.ad a.quiet:hover {
  color: npmred;
}
```

The variable has not been replaced. The order of `import` is important.

**Comment by aredridel** [comment]
Aha! That is important then!

**Comment by aredridel** [comment]
LGTM then! Always nice to see what problem is being solved in the PR.

**Comment by aredridel** [comment]
Thank you!

**Pull request merged**
