### PR TITLE
Adding hover styles for global search

### PR DESCRIPTION
**Pull request by kenperkins**
This is a bit more opinionated, and not being fully versed in your visual design do so as you see fit. Also, I'm not 100% up to date on stylus convention, I think I've done this correctly.

Thoughts?

### CODE REVIEW

**Comment by kenperkins** [comment]
And there is evidence I don't know how to use stylus. /me goes to read docs.

**Comment by kenperkins** [comment]
On a closer look, this appears to be a random timeout with travis.

**Comment by kenperkins** [comment]
@zeke I think I need you to push a different button, the travis re-run build button.

**Comment by zeke** [comment]
Is there such a button? I always thought `git commit -m "nothing" --allow-empty && git push` was the button.

**Comment by kenperkins** [comment]
image

**Comment by kenperkins** [comment]
@zeke btw that's in travis's UX

**Comment by zeke** [comment]
Nice. I didn't see the button because I wasn't logged in.

**Comment by kenperkins** [comment]
@zeke do you have CI/CD setup for `newww` or is it manually pushed periodically? I noticed on the other bug it shipped same day :)

**Comment by zeke** [comment]
It's manual for now. I just deployed. :)

**Comment by kenperkins** [comment]
well then, clearly  `10%` wasn't darkened enough.

**Pull request merged**
