### PR TITLE
Add custom tutorial for each package

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by jonathanmarvens** [comment]
@aredridel: Can you push to staging, please?

**Comment by jonathanmarvens** [comment]
Oops, looks like @rockbot is a mind reader.

**Comment by aredridel** [comment]
1, I think makes sense, but I actually think we can push this to prod and refine, because I want @ashleygwilliams input.

2, I agree. I can just do that.

3. Yes indeed, let's push and refine.

**Comment by aredridel** [comment]
Discussed in triage: going to ship, then refine with @ashleygwilliams input. Will sync up with her.

**Pull request merged**
