### PR TITLE
fix includeSubdomains typo

### PR DESCRIPTION
**Pull request by tetsuo**
Looks like this should be `includeSubDomains` (http://hapijs.com/api)

### CODE REVIEW

**Comment by aredridel** [comment]
Sure enough! Thanks for catching this! Looks like it was documented wrong in hapi at one point, since fixed!

**Comment by aredridel** [comment]
... Whaaaat.  That actually crashes! Despite being documented!

**Comment by aredridel** [comment]
... Because that's in hapi 11, where this spelling is correct for 9. Augh!

**Comment by tetsuo** [comment]
Ah, my mistake, should've checked the version.

Looks like this is fixed very recently (https://github.com/hapijs/hapi/pull/2776)

**Pull request merged**
