### PR TITLE
Add Constructor.io autocomplete to search bar

### LINKED ISSUE #720: Add Typo-Tolerant Autocomplete with Constructor.io
Per emails with @isaacs @rockbot @zeke, [constructor.io](https://www.constructor.io) just needs an initialization dataset (can be two weeks of search queries, or just a list of current modules along with an optional score for each like num_downloads, or num_searches) in csv format of: <code> name, score </code>. You can create a free account at [constructor.io](https://www.constructor.io) and upload there.

Once [constructor.io](https://www.constructor.io) receives this, we'll have a working typo-tolerant autocomplete (that will learn and get even better over time) ready for you in a few hours that you can use on any pages you like by just inserting our client with two lines of javascript. Please ping me if you have any questions.

### PR DESCRIPTION
**Pull request by danmcc**
Closes #720  Hi guys -- Co-founder of Constructor.io here. @EliFinkelshteyn and I have an autocomplete all ready for you. Currently, we have it auto-completing to packages for your users who know exactly what they're looking for, and to common searches for users who are looking more serendipitously.

Right now, we have you on the ad-based/branded plan, but we'd be happy to talk about taking you off of that and moving to something else, if you'd prefer.

Finally, we just made some basic styling for your current autocomplete, thinking you'd be likely to change it. That's very easy to do with css (in _header.styl), if you're interested. Otherwise, you're more than welcome to use everything as is. Please let us know if you have any questions, comments, or concerns!

### CODE REVIEW

**Comment by zeke** [comment]
Hi @danmcc. I finally had a chance to take a peek at this. Pretty cool! Here's some feedback:

- The package name results are great. It's really nice to jump straight to a package without the interstitial results screen.
- For the queries I'm typing, I find that the suggested queries are not especially useful. It's also not necessary to show a single suggested result if it exactly matches my current input.
- The results are linking to `npmjs.com`, even though I'm testing on localhost. There's a `canonicalHost` property in the server view context that we could easily make available in a `<meta>` tag or attach to `window`.
- The styles could use a little polishing. I would prefer that the `.autcomplete-suggestions` element be more aligned with the search input, perhaps along its bottom edge, and spanning the full width of the input. I'd be happy to help get this polished. :)
- I think we're happy to have the "Powered by Contructor.io" thing at the bottom, but I'd like to work on the styles for that a bit too.

Lastly, we are just about to merge the long-lived `r2` branch to master. A lot will change, namely the content security policy file, so this PR will need some TLC to be mergeable. Luckily it's a pretty small PR so it shouldn't be too much work.

Here are some screenshots for posterity, and for the benefit of those who want to see what this looks like without getting it up and running:

screen shot 2015-04-02 at 11 14 12 am

screen shot 2015-04-02 at 11 17 30 am

screen shot 2015-04-02 at 11 24 29 am

**Comment by danmcc** [comment]
Thanks @zeke !   Glad you like it.

* Re: suggested queries.  We're open to modifying them, but suspect that users who don't know the name of the package they're looking for will find them useful.  We can look at how people end up interacting with them and adjust accordingly, if that sounds good to you guys.
* Re: showing single suggestions, I know it feels redundant, but we've found users find it reassuring to have their result come up in autocomplete even if it's an exact match, as it shows them that their search is expected and makes sense. When the exact result is not shown, customers begin to think they might be using the wrong term
* Re: where the results link.  Good call.  We'll start returning relative URLs, which should solve the problem, if that sounds good.
* Re: autosuggest styling.  Also a good call.  We'll implement your suggestions, and then you're welcome to further tweak from there.
* Re: branding styling.  Let us know if you have anything specific in mind.  We're happy to work with you on it.

Thanks for all the good comments.  We'll start looking at r2 and get the PR ready for it.

**Comment by zeke** [comment]
:+1:

**Comment by danmcc** [comment]
Hi @zeke.  We've been hoping to update this PR but it sounds like (#761) it's hard to get everything running outside your environment.  From poking around, it looks like updating the CSP files should be most of the work.  Is there anything we can do to help?

**Comment by danmcc** [comment]
Thanks @rockbot!  We've rebased with master.  Hopefully this should work straightaway, but let us know how it looks on staging!

**Comment by danmcc** [comment]
Thanks again @rockbot!  Looks like we messed up the CSP rules a little (at least, that's what Chrome tells us).  Here's another stab at it.

**Comment by EliFinkelshteyn** [comment]
No problem at all for us. We wanted to give you guys a nice default to start with, but please style however you like. Thank you for the extremely fast follow-ups! Let us know if there's anything we can do to help.

**Comment by EliFinkelshteyn** [comment]
Definitely. We'll get it done.

**Comment by danmcc** [comment]
Hello @rockbot!  Ok, the "powered by Constructor.io" is now in a div with the id #powered-by-constructor-io, and you can change the background color with that CSS selector.  As for sizing, you can alter the width of the box by passing in a "width" parameter in the call to constructorAutocomplete ([here](https://github.com/npm/newww/pull/747/files#diff-4c74f79e618d8bf76f71f05bfb654afeR3), after maxHeight).  You can also adjust the positioning of the suggestions themselves by modifying the margin-top and margin-left properties of .autocomplete-suggestions.

Let us know if there's anything else we can help with!

**Pull request closed without merging**
