### PR TITLE
Marketing sidebar blob

### PR DESCRIPTION
**Pull request by isaacs**
Sort of like the CMS-driven upsell box, but way smaller, and fewer features.

Deployamating to stage coach presently.

### CODE REVIEW

**Comment by bcoe** [comment]
can we feature flag this so that it doesn't show up in npm On-Site? or better still, is there something useful it could show in On-Site?

**Comment by isaacs** [comment]
Feature-flagging out of on-site is a great idea. :+1:

**Comment by aredridel** [comment]
LGTM pending feature flagging.

**Comment by aredridel** [comment]
LGTM!

**Comment by bcoe** [comment]
thanks for the npmo check \o/

**Pull request merged**
