### PR TITLE
First pass at basic /registry/<package>.rss route.

### PR DESCRIPTION
**Pull request by DavidSouther**
Solution for #121 

This is a first pass, mostly to try playing with newww. It's a feature I think would be really useful. Not sure long term support or issues with it, but here's a first blush.

The registry facet gets a new route, `/registry/{package}.rss`, that returns an rss xml with reach release as an `<item>`. Long term, I'd like to see options for "deep" notifications, generating items for each dependency update as well. This way, you could subscribe to the "master" rss feed for your package, and know when your deps are updated to run tests or re-release or whatever.

### CODE REVIEW

**Comment by zeke** [comment]
Hey @DavidSouther, now that newww has shipped and is stabilizing, it would be awesome to see this feature land on the site. Any interesting in bringing this PR up to date?

**Comment by DavidSouther** [comment]
Absolutely! I've got some time today and this weekend - if you don't hear from my by Monday or Tuesday, want to ping me then?

**Comment by zeke** [comment]
Sounds good. :)

**Comment by zeke** [comment]
@DavidSouther I'm spring cleaning this PR. Feel free to update and re-open at a later time.

**Pull request closed without merging**
