### PR TITLE
Adds style for tables in readme section

### PR DESCRIPTION
**Pull request by mikaelbr**
The tables in the READMEs looked a bit off without any styling. I tried to add a style similar to the code block styles, with a #f5f5f5 background and some padding.

I don't know what kind of style you are going for here. Do you think the background looks OK, or should it simply have borders or no background at all?

---

### Before
tablebefore
---
### After
tableafter

### CODE REVIEW

**Comment by numtel** [comment]
I came here to write a very similar PR. The screenshot looks very good. Anything is better than the current no-style.

**Comment by fvdm** [comment]
I agree, the tables **need** styling asap!
They are barely readable.

**Comment by zeke** [comment]
Shipping this and keeping the conversation going at https://github.com/npm/newww/issues/545

**Comment by fvdm** [comment]
Thanks, @zeke !

**Pull request merged**
