### PR TITLE
adding auto focus issue #548

### PR DESCRIPTION
**Pull request by bmullan91**

### CODE REVIEW

**Comment by andineck** [comment]
+1

**Comment by aredridel** [comment]
autofocus wrecks accessibility, but you can type "/" to focus the field on the page!

**Comment by andineck** [comment]
thx, for the tip, didn't know. Is that a common thing working on different websites?

**Comment by aredridel** [comment]
Many, particularly sites written by unix using geeks. Also, tab can select the first thing in many browsers.

**Comment by andineck** [comment]
:-) cool, will check, only tried tab so far.

**Pull request merged**
