### PR TITLE
Fix navigation alignment

### LINKED ISSUE #1681: magic number in nav CSS
looks like the first anchor element is left aligned, while all others are right aligned
this supports the idea that the first anchor will be the npm-expansions anchor, but this is not always true

e.g.

```
nav
  div.container
    a(href="http://www.npmjs.com/on-site") npm On-Site
    a(href="https://www.npmjs.com/private-packages") npm Private Packages
    a(href="https://www.npmjs.com/open-source") npm Open Source
    a(href="https://www.npmjs.com/support") support
```

produces 
screenshot 2015-12-18 at 4 54 04 pm

### PR DESCRIPTION
**Pull request by ncawthon**
fixes #1681

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hey @ncawthon would you mind putting the issue number in the body and not the PR title? it adds a reference to the issue automatically which is nice, and will close the issue when the branch is merged. putting it in the title is confusing (at least, to me).

**Comment by aredridel** [comment]
Should probably rebase this to get good commit messages, and figure out what's up with the tests. Let's pair and I can help you practice a git rebase to square this u.

**Comment by aredridel** [comment]
There are also merge markers in here. Needs code review.

**Comment by aredridel** [comment]
And this has lots of merge conflicts. This is gonna need some work to fix up, closing for now. Can open a new PR.

**Pull request closed without merging**
