### PR TITLE
Make clear button be accessible on small screens

### PR DESCRIPTION
**Pull request by alrra**
On small screens the search input slides under the submit button, thus, preventing the clear button (provided by some browsers) to be accessible.

| Before | After |
|:---:|:---:|
|  |  |

| Before | After |
|:---:|:---:|
|  |  |

### CODE REVIEW

**Comment by alrra** [comment]
> what browsers/devices did you test this on?

--

> 
| Before | After |
|:---:|:---:|
|  |  |

:arrow_up: are from the latest Chrome for Android (device: [Samsung Galaxy S III](https://en.wikipedia.org/wiki/Samsung_Galaxy_S_III)).

> | Before | After |
|:---:|:---:|
|  |  |

:arrow_up: are from the latest Chrome on OS X, but the issue can be seen in all browsers that have the clear functionality (e.g.: Safari, newer IEs etc.)

--

> I'm unable to recreate the bug or see the fix :-/

@rockbot Modern browsers will display a [clear button](https://www.youtube.com/watch?v=RA9wd9q1Ydg&t=30s) () when text is entered in the input search field.

In the case of `npmjs.com`, if the width of the browser viewport is small (which is the case with mobile devices with smaller screens), the user will not be able to tap / click that clear button as it will be under the submit input, and therefore, not accessible.

**Comment by alrra** [comment]
>  and it's not quite working... Want to take a look and try to figure out what might be going on?

@rockbot The problem is that the [`index.css`](https://staging.npmjs.com/static/css/index.css) file from `https://staging.npmjs.com` does not include the changes from this pull request.

Note: I can [only run certain parts of the build process](https://github.com/npm/newww/issues/761), however, the part that is also responsible with [regenerating](https://github.com/npm/newww/blob/869aa65a5c39f57d1b67376059d431b98b4a998f/gulpfile.js#L47-L51) the `index.css` file (namely  `npm run prepublish`) works for me, and correctly [includes the new content from `_header.styl`](https://github.com/npm/newww/blob/a8880feb3534529b1853de498a37d11a0df2485d/assets/styles/index.styl#L7).

**Comment by alrra** [comment]
> I pushed this branch up to our staging server (https://staging.npmjs.com), and it's not quite working.

@rockbot It now works on https://staging.npmjs.com/  :tada: 



--

@rockbot Based on the [previous similar problem](https://github.com/npm/newww/pull/1026#issuecomment-109420258) and [this one](https://github.com/npm/newww/pull/1074#issuecomment-120141716), could it be that there is some internal caching related issue?

**Comment by alrra** [comment]
> It now works on https://staging.npmjs.com/ :tada:

:arrow_up: Not true anymore as the [`deploy-staging`](https://github.com/npm/newww/tree/deploy-staging)  branch (and thus, https://staging.npmjs.com/) no longer include the changes from this pull request.

**Comment by alrra** [comment]
@rockbot @jefflembeck When you have time, can you take another look at this pull request? Thanks!

**Comment by alrra** [comment]
@rockbot @jefflembeck @aredridel When you have time, can you take another look at this pull request? Thanks!

**Comment by aredridel** [comment]
I'd be happy to -- did you intend to close this?

**Comment by alrra** [comment]
> did you intend to close this?

@aredridel Yes. After seeing that there is no activity / interest related to the simple pull requests that I've opened in most cases a few months ago (e.g.: [1](https://github.com/npm/newww/pull/1014), [2](https://github.com/npm/newww/pull/1013), [3](https://github.com/npm/newww/pull/1119), ...), I considered that at this point it was better to just close them.

**Comment by aredridel** [comment]
Ah! Things have not moved particularly fast on this project -- I was just added to the team, so now we've more bandwidth to look at things like this.

**Pull request closed without merging**
